---
chain_minimum_gas_prices: "0.001uosmo"
chain_addrbook_url: https://quicksync.io/addrbook.osmosis.json
quicksync_available: true
chain_version: v11.0.0
chain_bin_url: https://github.com/osmosis-labs/osmosis/releases/download/v11.0.0/osmosis-11.0.0-linux-amd64
