
---
chain_name: terra
chain_bin_flags: "--x-crisis-skip-assert-invariants"
chain_minimum_gas_prices: "0.01133uluna,0.15uusd,0.104938usdr,169.77ukrw,428.571umnt,0.125ueur,0.98ucny,16.37ujpy,0.11ugbp,10.88uinr,0.19ucad,0.14uchf,0.19uaud,0.2usgd,4.62uthb,1.25usek,1.25unok,0.9udkk,2180.0uidr,7.6uphp,1.17uhkd"
chain_addrbook_url: https://quicksync.io/addrbook.terra.json
quicksync_available: true