---
name: Test Cosmos role (osmosis)

on:
  pull_request:
    branches:
      - main
    paths:
      - roles/blockbook/**
      - molecule/blockbook/**

permissions:
  id-token: write
  contents: read

env:
  MOLECULE_SCENARIO: blockbook

jobs:
  ansible-galaxy:
    name: "ansible-galaxy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Confiugre AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      # role has dependency during testing with Molecule which is not resolved
      # for some reason --role-path specified during molecule run is not used during prepare play
      # maybe it's a molecule-ec2 package issue
      - run: ansible-galaxy role install -vr requirements.yml

      - name: Test role with Molecule
        if: github.repository_owner == 'trustwallet'
        run: molecule -v test -s $MOLECULE_SCENARIO
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          MOLECULE_VPC_SUBNET_ID: ${{ secrets.MOLECULE_VPC_SUBNET_ID }}
          MOLECULE_IMAGE_DEBIAN: ${{ secrets.MOLECULE_IMAGE_DEBIAN }}
          BLOCKBOOK_CHAIN_NAME: firo
